### ISSUE TITLE
Feature Request: Recursive search for tests in test directory

### ISSUE THREAD

**Issue by michaeltryby** [davidchall/nrtest#12]
A recursive search for tests in the test directory would allow groups of related tests to be organized into sub folders. This would also make it easy to run a subset of tests when desired.

**Comment by davidchall** [comment]
Hi @michaeltryby, I agree this would be a good feature. This would need to be careful to correctly track relative paths to input files.

I might not be able to work on this until about mid-October though. If you have something that works, please open a pull request and I will review and accept.
