### ISSUE TITLE
Persist result of benchmark comparison in a "receipt.json" file 

### ISSUE THREAD

**Issue by michaeltryby** [davidchall/nrtest#17]
@davidchall We have deployed `nrtest` in our CI workflow. It's working great! 

It would be super useful to create a record of the benchmark comparison result that could be processed post-test so that artifacts from failing tests could be cached for retrieval. This would aid the debugging process and would also be useful for generating QA/QC documentation. 

I would like to create a file to persist benchmark comparisons. Maybe call it "receipt.json". Do you have any thoughts or preferences on how such a feature should be implemented? What information do you think the file should contain and where should it be saved? 

I was thinking of something like this: 
```json
receipt.json
{
    "Benchmarks": [
        {
            "new_benchmark": "EPANET220"
        }, 
        {
            "old_benchmark": "EPANET2012"
        }

    ],
    "precision": {
        "relative tolerance":"0.10",
        "absolute tolerance":"0.00"
    },
   "Tests": [
        {
            "description": "A simple example of modeling chlorine decay",
            "name": "Example 1",
            "output_files": {
                "example1.out": "epanet allclose",
                "example1.rpt": "epanet report"
            },
            "passed": true,
            "error_msg": "null"
        },
        {
            "description": "Example of modeling a 55-hour fluoride tracer study.",
            "name": "Example 2",
            "output_files": {
                "example2.out": "epanet allclose",
                "example2.rpt": "epanet report"
            },
            "passed": false,
            "error_msg": "Unexpected error occurred during diff"
        }
    ]
}
```
Thanks for your input.

**Comment by davidchall** [comment]
Hi Michael, I really like this idea! It could also be used by a dashboard to display the latest test results. 

I'll put something together very soon and open a PR for discussion.

**Comment by michaeltryby** [comment]
@davidchall Just updated to nrtest 0.2.3 and got the new benchmark comparison result file feature running. Works great! We really appreciate it!
