### ISSUE TITLE
Feature Request: Filter tests by comparing test and app version tags

### ISSUE THREAD

**Issue by michaeltryby** [davidchall/nrtest#24]
@davidchall Hope you are well. :smile: I had an idea for a feature I wanted to run by you. 

When dealing with a large collection of regression test input files and many different versions of an application, it would be useful to filter tests by the minimum app version required to run it. 

Input files are referenced in `test.json` configuration files used by `nrtest`. Input files formats have a tendency to change slowly over time as features get added to an application. It would be useful to perform a check making sure that an input file is compatible with the version of the application executing it. This would help weed out false test failures related to input file format incompatibilities. 

This could be implemented by comparing the test version and app version tags when processing tests for execution.

**Comment by davidchall** [comment]
Hi @michaeltryby - this feature sounds useful. The minimum app version required for a test could also be used when comparing benchmarks.

One question I've been meaning to ask you is which Python version you run your test suite with? If I could drop support for Python 2, this would make maintenance easier. And if I could require Python 3.7, then I could make use of [data classes](https://docs.python.org/3/library/dataclasses.html).

**Comment by michaeltryby** [comment]
Hey @davidchall! Yeah this feature has the potential to simplify management of our regression testing workflow. 

Right now we have our input files under source code control and tagged by version. Version comparison would allow us to maintain a mixed bag of regression tests that nrtest could sort at execution time. This would help simplify our process for staging reg tests on build workers and our SOPs for adding and maintaining them. 

Anyhow, we have migrated away from Python 2.7 and are currently using Python 3.7. I hadn't heard of data classes but they look useful. Thanks!
